# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Applications/CMake 2.8-9.app/Contents/bin/cmake"

# The command to remove a file.
RM = "/Applications/CMake 2.8-9.app/Contents/bin/cmake" -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "/Applications/CMake 2.8-9.app/Contents/bin/ccmake"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/masahiko/Programs/objectPoseEstimation

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/masahiko/Programs/objectPoseEstimation

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"/Applications/CMake 2.8-9.app/Contents/bin/ccmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Applications/CMake 2.8-9.app/Contents/bin/cmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/masahiko/Programs/objectPoseEstimation/CMakeFiles /Users/masahiko/Programs/objectPoseEstimation/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/masahiko/Programs/objectPoseEstimation/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named learning

# Build rule for target.
learning: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 learning
.PHONY : learning

# fast build rule for target.
learning/fast:
	$(MAKE) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/build
.PHONY : learning/fast

#=============================================================================
# Target rules for targets named objectPoseEstimation

# Build rule for target.
objectPoseEstimation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 objectPoseEstimation
.PHONY : objectPoseEstimation

# fast build rule for target.
objectPoseEstimation/fast:
	$(MAKE) -f CMakeFiles/objectPoseEstimation.dir/build.make CMakeFiles/objectPoseEstimation.dir/build
.PHONY : objectPoseEstimation/fast

CDataset.o: CDataset.cpp.o
.PHONY : CDataset.o

# target to build an object file
CDataset.cpp.o:
	$(MAKE) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/CDataset.cpp.o
.PHONY : CDataset.cpp.o

CDataset.i: CDataset.cpp.i
.PHONY : CDataset.i

# target to preprocess a source file
CDataset.cpp.i:
	$(MAKE) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/CDataset.cpp.i
.PHONY : CDataset.cpp.i

CDataset.s: CDataset.cpp.s
.PHONY : CDataset.s

# target to generate assembly for a file
CDataset.cpp.s:
	$(MAKE) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/CDataset.cpp.s
.PHONY : CDataset.cpp.s

CPatch.o: CPatch.cpp.o
.PHONY : CPatch.o

# target to build an object file
CPatch.cpp.o:
	$(MAKE) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/CPatch.cpp.o
.PHONY : CPatch.cpp.o

CPatch.i: CPatch.cpp.i
.PHONY : CPatch.i

# target to preprocess a source file
CPatch.cpp.i:
	$(MAKE) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/CPatch.cpp.i
.PHONY : CPatch.cpp.i

CPatch.s: CPatch.cpp.s
.PHONY : CPatch.s

# target to generate assembly for a file
CPatch.cpp.s:
	$(MAKE) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/CPatch.cpp.s
.PHONY : CPatch.cpp.s

learning.o: learning.cpp.o
.PHONY : learning.o

# target to build an object file
learning.cpp.o:
	$(MAKE) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/learning.cpp.o
.PHONY : learning.cpp.o

learning.i: learning.cpp.i
.PHONY : learning.i

# target to preprocess a source file
learning.cpp.i:
	$(MAKE) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/learning.cpp.i
.PHONY : learning.cpp.i

learning.s: learning.cpp.s
.PHONY : learning.s

# target to generate assembly for a file
learning.cpp.s:
	$(MAKE) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/learning.cpp.s
.PHONY : learning.cpp.s

loadConfig.o: loadConfig.cpp.o
.PHONY : loadConfig.o

# target to build an object file
loadConfig.cpp.o:
	$(MAKE) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/loadConfig.cpp.o
.PHONY : loadConfig.cpp.o

loadConfig.i: loadConfig.cpp.i
.PHONY : loadConfig.i

# target to preprocess a source file
loadConfig.cpp.i:
	$(MAKE) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/loadConfig.cpp.i
.PHONY : loadConfig.cpp.i

loadConfig.s: loadConfig.cpp.s
.PHONY : loadConfig.s

# target to generate assembly for a file
loadConfig.cpp.s:
	$(MAKE) -f CMakeFiles/learning.dir/build.make CMakeFiles/learning.dir/loadConfig.cpp.s
.PHONY : loadConfig.cpp.s

objectPoseEstimation.o: objectPoseEstimation.cpp.o
.PHONY : objectPoseEstimation.o

# target to build an object file
objectPoseEstimation.cpp.o:
	$(MAKE) -f CMakeFiles/objectPoseEstimation.dir/build.make CMakeFiles/objectPoseEstimation.dir/objectPoseEstimation.cpp.o
.PHONY : objectPoseEstimation.cpp.o

objectPoseEstimation.i: objectPoseEstimation.cpp.i
.PHONY : objectPoseEstimation.i

# target to preprocess a source file
objectPoseEstimation.cpp.i:
	$(MAKE) -f CMakeFiles/objectPoseEstimation.dir/build.make CMakeFiles/objectPoseEstimation.dir/objectPoseEstimation.cpp.i
.PHONY : objectPoseEstimation.cpp.i

objectPoseEstimation.s: objectPoseEstimation.cpp.s
.PHONY : objectPoseEstimation.s

# target to generate assembly for a file
objectPoseEstimation.cpp.s:
	$(MAKE) -f CMakeFiles/objectPoseEstimation.dir/build.make CMakeFiles/objectPoseEstimation.dir/objectPoseEstimation.cpp.s
.PHONY : objectPoseEstimation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... learning"
	@echo "... objectPoseEstimation"
	@echo "... rebuild_cache"
	@echo "... CDataset.o"
	@echo "... CDataset.i"
	@echo "... CDataset.s"
	@echo "... CPatch.o"
	@echo "... CPatch.i"
	@echo "... CPatch.s"
	@echo "... learning.o"
	@echo "... learning.i"
	@echo "... learning.s"
	@echo "... loadConfig.o"
	@echo "... loadConfig.i"
	@echo "... loadConfig.s"
	@echo "... objectPoseEstimation.o"
	@echo "... objectPoseEstimation.i"
	@echo "... objectPoseEstimation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

